name: Run OpenCode with Prompt

on:
  push:
    paths:
      - 'prompt.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          sudo apt install -y python3 python3-pip chromium-browser
          pip3 install websocket-client

      - name: Make script executable
        run: chmod +x mulai.sh

      - name: Run tests
        run: ./mulai.sh

      - name: upload hasil
        uses: actions/upload-artifact@v4
        with:
          name: hasil_hunting
          path: '**/*.md'
          if-no-files-found: error
